# Better Invisibility Configuration

hide:
  helment: true
  chestplate: true
  leggings: true
  boots: true
  mainhand: true
  offhand: true
  potionParticles: false

# Currently every time invisible players get hit, they will appear visible for a split second for the hit animation but
# there is a workaround but this will make the invisible player have same knockback from every attack (custom knockback)
enable_workaround: false
