name: BetterInvisibility
version: '1.0'
main: newamazingpvp.betterinvisibility.BetterInvisibility
api-version: 1.18
authors: [ NewAmazingPVP ]
description: Improves Invisibility in Minecraft by many ways!
depend:
  - ProtocolLib
