name: BetterInvisibility
version: '4.0.0'
main: newamazingpvp.betterinvisibility.BetterInvisibility
api-version: 1.13
authors: [ NewAmazingPVP ]
description: Improves Invisibility in Minecraft by many ways!
depend:
  - PacketEvents